function f_step = system_solid_com(r_step, y_step, n, G, rho, rho_profile, ...
    mu, lambda, r_in_core, r_out_core, r_mantle)

%elastic parameters in the current step
A = lambda + 2*mu;
K = lambda + 2*mu/3;

g = get_g(r_step, r_in_core, r_out_core, r_mantle, rho_profile, G);

%matrix 6x3
M = [-2*lambda/(A*r_step), lambda*n*(n+1)/(A*r_step), 1/A, 0, 0, 0;
    ...
    -1/r_step, 1/r_step, 0, 1/mu, 0, 0;
    ...
    (4/r_step)*((mu*3*K/(r_step*A)) - rho*g), (n*(n+1)/r_step)*...
    (rho*g - (2*mu*3*K/(r_step*A))), -4*mu/(A*r_step), ...
    n*(n+1)/r_step, -rho*(n+1)/r_step, rho;
    ...
    (1/r_step)*(rho*g - (2*mu*3*K/(r_step*A))), ...
    (2*mu/(r_step^2))*(2*n*(n+1)*(lambda+mu)/A - 1), ...
    -lambda/(A*r_step), -3/r_step, rho/r_step, 0;
    ...
    -4*pi*G*rho, 0, 0, 0, -(n+1)/r_step, 1;
    ...
    -4*pi*G*rho*(n+1)/r_step, 4*pi*G*rho*n*(n+1)/r_step, 0, 0, 0, (n-1)/r_step];

f_step = M * (y_step)';

end